### ISSUE TITLE
generic name

### ISSUE THREAD

**Issue by BitesizedLion** [iAverages/iAverages#1]
ur first name is too generic

**Comment by BitesizedLion** [comment]
https://user-images.githubusercontent.com/42980888/114250576-70b93300-999e-11eb-88c1-514b2a94a6a0.mp4

**Comment by iAverages** [comment]
what

**Comment by BitesizedLion** [comment]
> 
> 
> what

yes its issue

**Comment by BitesizedLion** [comment]
https://user-images.githubusercontent.com/42980888/114250664-bd047300-999e-11eb-9aac-b94aa4f130ea.mp4

**Comment by iAverages** [comment]
fixed. wait 100000 years and it'll update

**Comment by BitesizedLion** [comment]
is not resolvkeddd

**Comment by BitesizedLion** [comment]
sir

**Comment by BitesizedLion** [comment]
### 

> [`_****_`](

- 

- [x] is not resolved sir

)

**Comment by iAverages** [comment]
sir. "fixed. wait 100000 years and it'll update"

**Comment by BitesizedLion** [comment]
sir, i die in i 1000000000 years

**Comment by iAverages** [comment]
ok

**Comment by BitesizedLion** [comment]
### 

> 

> [`_**faster**_`](faster)
